### ISSUE TITLE
Healing Powder Causing Fatness/Blubberness, Breaking Values.

### ISSUE THREAD

**Issue by MarkValentinee** [Drymouth-Gulch/Drymouth-Gulch#146] opened 2017-09-01 02:28 UTC
![1cbfa00aa6b7eeec0f744d300a0b3467](https://user-images.githubusercontent.com/31527318/29953089-6a2a8460-8e9b-11e7-9558-423e4e115c19.png)

So basically I usually play Legion, and we're only allowed to use Healing Powder. Healing Powder isn't consumed, its rubbed on the wounds in order to seal them up. Now when you use around four-five at once it for some reason causes fatness to occur, and eventually blubbiness. This shouldn't be happening as it isn't consumed by eating, its applying like a Stimpack.

As you can see from the Admin I was speaking with verified this, the value broke from the 600 limit to 1000.

**Comment by namjay1170** [comment] 2017-09-01 05:17
The crafting code we use was /mostly/ made for food, it takes the reagents of the base chemicals used to make it, ie broc and xander (nutrients and saline glucose) and adds it to the finished product on top of the chemicals that are added from crafting, this was intended to make it when you craft the food if the ingredients were high quality it would make the food a higher quality dish.

**Comment by LR001** [comment] 2017-09-03 01:02
fixed in #151 Xander and Broc are now fully healing plants and serve no nutritional value..

**Closed by LR001** 2017-09-03 01:02 UTC
Labels: bug
